#!/bin/bash
name=(putchar
islower
isalpha
abs
isupper
isdigit
strlen
puts
strcpy
atoi
strcat
strncat
strncpy
strcmp
memset
memcpy
strchr
strspn
strpbrk
strstr
)
i=1
for t in ${name[@]}; do
	cp $(find .. -name *$t*.c | head -1) .
	if command;then
		echo OK $i
	else
		echo DID NOT FIND NUMBER $i: $(find .. -name *$t*.c | head -1)
	fi
	i=$((i+1))
done
